language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install -g npm@2


#before_script:
 # - npm install -g gulp

before_install:
  - npm install -g gulp
  - npm install -g hexo
  - npm install -g hexo-cli

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ilxj"
  - git config user.email "linxiaoj@126.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: git@github.com:ilxj/demo.git